### ISSUE TITLE
Bitdefender Internet Security prevents tool execution

### ISSUE THREAD

**Issue by b-morgan** [LiaNdrY/Enshrouded-Tool-Fix#2]
PS C:\Users\Brad\Downloads> irm "https://raw.githubusercontent.com/LiaNdrY/Enshrouded-Tool-Fix/main/Enshrouded_Tool_Fix.ps1" | iex
At line:1 char:1
+ irm "https://raw.githubusercontent.com/LiaNdrY/Enshrouded-Tool-Fix/ma ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

Downloading and executing the file locally gets further but Bitdefender still blocks execution.

**Comment by LiaNdrY** [comment]
I don’t know what he found there in the first line, in the first character. The first line is just a comment. I think it's easier to disable it while the script is running.

**Comment by steel-raven** [comment]
It could be that he uses Advanced Threat Defense, which is known to block PS scripts afaik.
