### ISSUE TITLE
After Running the tool and restarting the PC I'm unable to launch the game

### ISSUE THREAD

**Issue by Okimo** [LiaNdrY/Enshrouded-Tool-Fix#3]
I'm on the latest Intel Arc Drivers
![image](https://github.com/LiaNdrY/Enshrouded-Tool-Fix/assets/12627805/d9ad5960-3728-4f78-927c-2fa37ffe47fd)

Found this command to check the Vulkan Version - seems like the update that's part of the tool messed up the files.
![image](https://github.com/LiaNdrY/Enshrouded-Tool-Fix/assets/12627805/f15d8e35-ac05-4849-957f-7b070a2f7194)

Log file from the Tool (Also the tool doesn't recognize Intel graphics)
[Enshrouded_Tool_Fix_2024-03-29T13-04-54.log](https://github.com/LiaNdrY/Enshrouded-Tool-Fix/files/14804170/Enshrouded_Tool_Fix_2024-03-29T13-04-54.log)

System info:
Arc A770 LE (16GB) (Driver 31.0.101.5379)
AMD R5 5600X
32 GB of Ram
Windows 11 (build 22635)

**Comment by LiaNdrY** [comment]
The script couldn't break anything, it simply updated the standard Vulkan library to the latest version, you essentially could do the same thing, only with your hands. The fact that he did not recognize the Intel video card is only half true; if he recognized it, he would simply provide links to new drivers and nothing more. Just try to reinstall the drivers for the video card, they will overwrite the new version of Vulkan with the old one and try running vulkaninfo again.

**Comment by Okimo** [comment]
Yup reinstalling the drivers installed the older version of Vulkan library and made the game run again.
Also output from vulkaininfo command :)
[Vulkaninfo.log](https://github.com/LiaNdrY/Enshrouded-Tool-Fix/files/14804893/Vulkaninfo.log)

**Comment by LiaNdrY** [comment]
This means your video card cannot work with the latest version of Vulkan RT, you can try to manually find and install the version (closer to the latest) on which your video card will work correctly.

https://vulkan.lunarg.com/sdk/home
